### ISSUE TITLE
TypeError: serverless.configSchemaHandler.defineFunctionProperties is not a function

### ISSUE THREAD

**Issue by yoedikurniawan** [abemedia/serverless-disable-functions#44]
Hi im using this plugins version v1.0.0 with tools versions as follow

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.11.0
     Framework Version:         1.83.3 (local)
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9

but still receives error 

TypeError: serverless.configSchemaHandler.defineFunctionProperties is not a function
      at /home/travis/build/deliveryhero/fp-apac-nimbus-service/node_modules/serverless-disable-functions/src/index.js:23:38
      at Array.forEach (<anonymous>)
      at new ServerlessDisableFunctionPlugin (/home/travis/build/deliveryhero/fp-apac-nimbus-service/node_modules/serverless-disable-functions/src/index.js:22:15)
      at PluginManager.addPlugin (/home/travis/build/deliveryhero/fp-apac-nimbus-service/node_modules/serverless/lib/classes/PluginManager.js:94:28)
      at /home/travis/build/deliveryhero/fp-apac-nimbus-service/node_modules/serverless/lib/classes/PluginManager.js:129:31
      at Array.forEach (<anonymous>)
      at PluginManager.loadAllPlugins (/home/travis/build/deliveryhero/fp-apac-nimbus-service/node_modules/serverless/lib/classes/PluginManager.js:129:8)
      at /home/travis/build/deliveryhero/fp-apac-nimbus-service/node_modules/serverless/lib/Serverless.js:88:39
  From previous event:
      at /home/travis/build/deliveryhero/fp-apac-nimbus-service/node_modules/serverless/lib/Serverless.js:86:12
      at processImmediate (internal/timers.js:439:21)
  From previous event:
      at Serverless.init (/home/travis/build/deliveryhero/fp-apac-nimbus-service/node_modules/serverless/lib/Serverless.js:78:8)
      at Object.<anonymous> (/home/travis/build/deliveryhero/fp-apac-nimbus-service/node_modules/serverless/scripts/serverless.js:54:4)
      at Module._compile (internal/modules/cjs/loader.js:945:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
      at Module.load (internal/modules/cjs/loader.js:798:32)
      at Function.Module._load (internal/modules/cjs/loader.js:711:12)
      at Module.require (internal/modules/cjs/loader.js:838:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/home/travis/build/deliveryhero/fp-apac-nimbus-service/node_modules/serverless/bin/serverless.js:41:1)
      at Module._compile (internal/modules/cjs/loader.js:945:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
      at Module.load (internal/modules/cjs/loader.js:798:32)
      at Function.Module._load (internal/modules/cjs/loader.js:711:12)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
      at internal/main/run_main_module.js:17:11

**Comment by abemedia** [comment]
I can't seem to reproduce this error. Are you certain you're on 1.0.0?

**Comment by ralphcode** [comment]
@abemedia I am having the same issue here;

```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.22.1
     Framework Version:         1.83.2 (local)
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9
```

**package.json**
`    "serverless-disable-functions": "^1.0.0",`


**serverless.yml**
```
plugins:
  - serverless-disable-functions
```


If I remove `serverless-disable-functions` from the plugins, everything runs as expected.

Any suggestions on what we can try?

Cheers,

**Comment by zelch** [comment]
The plugin requires a newer version of the serverless framework, 1.83.1 and 1.83.2 are still on the ancient 1.x code base.

The plugin requires at least v2.
